### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [ItsMari0/Project_Kinozal-Template#1]
1)
ссылка не работает, задание не выполнено
![image](https://user-images.githubusercontent.com/8464662/155332112-567d637d-ab74-4200-8498-269b50b69896.png)

**Comment by ItsMari0** [comment]
Все исправлено.
[https://itsmari0.github.io/Project_Kinozal-Template/page.html](url)
[https://github.com/ItsMari0/Project_Kinozal-Template](url)

**Comment by Alecto** [comment]
2)
допускаются отступы в 2 или в 4 пробела, но одинаково для всех файлов, включая css и js
![image](https://user-images.githubusercontent.com/8464662/156185963-26227bd7-9c98-4adc-8a69-fa2d67b32b18.png)

присылайте ссылки через почту, через гитхаб они не работают и нет ФИО, группы

**Comment by ItsMari0** [comment]
> допускаются отступы в 2 или в 4 пробела, но одинаково для всех файлов, включая css и js ![image](https://user-images.githubusercontent.com/8464662/156185963-26227bd7-9c98-4adc-8a69-fa2d67b32b18.png)
> 
> присылайте ссылки через почту, через гитхаб они не работают и нет ФИО, группы

Обновил разметку.

**Comment by Alecto** [comment]
для сдачи проекта присылайте две ссылки на почту, с указание ФИО и группы

пт, 4 бер. 2022 р. о 12:57 ItsMari0 ***@***.***> пише:
